language: cpp

branches:
  only:
    - main

dist: bionic

addons:
  apt:
    packages:
    - cmake
    - make
    - g++
    - pkg-config
    - libsdl2-dev
    - libsdl2-image-dev
    - libsdl2-ttf-dev
    - libsdl2-mixer-dev

# Build steps
script:
  - ./build_simple.sh
